package softlearning.core.component.order.domain.model;

public enum OrderStatus {
   CREATED,     //SOLO SE HA CREADO EL ORDER, PENDIENTE DE CONFIRMAD
   CONFIRMED,   //CARRITO VALIDADEO, PENDIENTE DE PAGO
   PAYED,       //ORDER PAGADO
   FORTHCOMMING,    //PREPARANDO EL PAQUETE, PENDIENTE DE ENVIO
   DELIVERED,   //ENVIO INICIADO CON DESTINO AL CLIENTE
   PENDING,     //PENDIENTE DE ENTREGA AL CLIENT
   FINISHED,    //ENVIO ENTREGADO AL CLIENT
   CANCELED     //ORDER CANCELADO
}
